### ISSUE TITLE
Search result for some series = No results.

### ISSUE THREAD

**Issue by tabarak105** [MefhigosetH/vikeep#18]
Hi
For example i'm looking for this series:
 " The King's Face - 왕의 얼굴 "
viki link :
viki.com/tv/24782c-the-kings-face
But in searching by various Of related word ( King ; face ; kings-face & ... ) 
result can't find this series 
when I manually Create a link , nothing happend Too
( vikeep.herokuapp.com/index.php?serie=24782c )
Then I must Add episode code from viki.com manually ( viki.com/videos/1055697v-the-kings-face-episode-1) To Your Address To can downloads that episode : (vikeep.herokuapp.com/index.php?episode=1055697v)
I know a few viki series only Shows in some Country .
is this related to viki area restricted ?

**Comment by MefhigosetH** [comment]
Hi @tabarak105 ,

This is true, some series are blocked to certain countries at Viki.com.

But, this issue is not the case. I make some test and found that this issue is related to the API_USER and API_SECRET that vikeep site use currently.

I would try to fix it, using other Viki API credentials. Keep in touch for news.

**Comment by MefhigosetH** [comment]
Hi @tabarak105,

I have touch the website source code to fix that you said. Now the search show more results and with paging.

BUT, we can't download episodes from King's Face for example. Only subtitles. I don't know why yet :-(

**Comment by tabarak105** [comment]
very very thanks for solving search result
